# Working with Numpy 

In [1]:
#installing the numpy linrarary
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
# importing the numpy with its alies name as np
import numpy as np


# #The central feature of NumPy is the array object class


In [3]:
 a = np.array([1, 4, 5, 8], float)

In [11]:
a

array([1., 4., 5., 8.])

In [8]:
type(a)

numpy.ndarray

In [13]:
a.shape

(4,)

In [14]:
 a.dtype

dtype('float64')

In [17]:
b=np.array([[1,2,3,],[4,5,6],[7,8,9]])


In [18]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.transpose(b)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Array mathematics

In [23]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)


In [25]:
#addition
c=a+b
print(c)

[6. 4. 9.]


In [26]:
#subtraction
c=a-b
print(c)

[-4.  0. -3.]


In [28]:
# multiplication
c= a*b
display(c)

array([ 5.,  4., 18.])

In [29]:
#division
c= a/b
display(c)

array([0.2, 1. , 0.5])

# Array iteration

In [40]:
 a = np.array([1, 4, 5], int)

In [41]:
for x in a:
    print(x)

1
4
5


In [44]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
      print(x)
           

[1. 2.]
[3. 4.]
[5. 6.]


In [45]:
for (x,y) in a:
      print(x*y)


2.0
12.0
30.0


# Vector and matrix mathematics

In [46]:
a = np.array([1, 2, 3], float)

In [47]:
 b = np.array([0, 1, 1], float)

In [48]:
# perform a dot product
np.dot(a,b)

5.0

In [49]:
# perform a cross product
np.cross(a,b)

array([-1., -1.,  1.])

 # Linear algebra calculations

In [50]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)

In [51]:
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [53]:
#calculating the deteminent of a matrix
np.linalg.det(a)

-48.00000000000003

In [55]:
# calculating the inverse of a matrix
b = np.linalg.inv(a)
print(b)

[[ 0.22916667  0.04166667 -0.29166667]
 [ 0.04166667 -0.08333333  0.58333333]
 [-0.3125      0.125       0.125     ]]


# Statistics

In [56]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)

In [57]:
# mean calculations
np.mean(a)


4.285714285714286

In [58]:
#meadon calculation
np.median(a)


3.0

In [62]:
 a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
print(c)


[[1.         0.72870505]
 [0.72870505 1.        ]]


In [64]:
#  correlation coefficient 
np.cov(a)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

# Random numbers

In [72]:
# setting seed value
np.random.seed(10)

In [79]:
# generating number(s)
a=np.random.rand(10)
print(a)

[0.0382722  0.0808424  0.08191454 0.80936733 0.800694   0.01690981
 0.86129433 0.91130022 0.40087668 0.2868907 ]


In [80]:
import pandas as pd

In [82]:
pd.df=a

In [86]:
a

array([0.0382722 , 0.0808424 , 0.08191454, 0.80936733, 0.800694  ,
       0.01690981, 0.86129433, 0.91130022, 0.40087668, 0.2868907 ])